### PR TITLE
Support for ExchangeOAuthCodeForAccessToken

### PR DESCRIPTION
**Pull request by markschmid**
I added support for the "ExchangeOAuthCodeForAccessToken" flow.
It's based on [this commit](https://github.com/FusionAuth/fusionauth-php-client/commit/fee9a29088f636e1c044cfbf18352e152588ad9d) in the PHP client library.

### CODE REVIEW

**Comment by robotdan** [comment]
As a side note - if you're using this library, we have a mechanism to build our domain as well. 

We generate these files from our Java domain.
https://github.com/FusionAuth/fusionauth-client-builder/tree/master/src/main/domain

It can then be used to build Go objects to keep them in sync. 

Our Typescript client just builds all of the type information into the main `FusionAuthClient` file, and our Net Core library builds separate files. Either approach is ok, my guess is that Go would want to take the approach used by the Net Core library. 
 
TypeScript
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/typescript.client.ftl

NetCore
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/netcore.domain.ftl

If you want to submit a PR for this feel free and then we can help maintain it.

**Comment by markschmid** [comment]
As this is essentially my first PR ever, I'd rather look into your building mechanism at a later stage if that's possible.

In regards to Basic Auth, I have tested my code successfully with the following conditions:

1) Basic Auth set to "required" in the FusionAuth Web UI (for the given Application)
- Calling ```ExchangeOAuthCodeForAccessToken()``` with the correct ```clientSecret```: Basic Auth is correctly encoded and ```access_token``` is provided.
- Calling ```ExchangeOAuthCodeForAccessToken()``` with a wrong ```clientSecret```: Encoded Basic Auth is not accepted by the ```/oauth2/token``` endpoint and an error message is shown (along the line "incorrect basic auth")
- Calling ```ExchangeOAuthCodeForAccessToken()``` with no ```clientSecret``` (```""``` in that case): No Authorization header is sent which is not accepted by the ```/oauth2/token``` endpoint and an error message is shown (along the line "missing basic auth")

2) Basic Auth NOT set to "required" in the FusionAuth Web UI (for the given Application)
- Calling ```ExchangeOAuthCodeForAccessToken()``` with no ```clientSecret``` (```""``` in that case): No Authorization header is sent. Accepted by the ```/oauth2/token``` endpoint and ```access_token``` is provided.

Let me know if there's something you'd like to have changed.

**Comment by robotdan** [comment]
No problem, I'll accept the PR and then copy the code into the template.  Thanks!

**Comment by robotdan** [comment]
See commit https://github.com/FusionAuth/fusionauth-client-builder/commit/d55d4c959e5fd7b24b0d08a57eb43640ed855f9e

Let me know if I missed something.

**Comment by markschmid** [comment]
Great, thanks! I think I now understand your client building mechanism. For any future contribution I'll try to PR directly to ```fusionauth-client-builder```.

**Pull request merged**
